name: smartcity
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Project dependencies

  upi_pay: ^1.0.4
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  intl: ^0.20.2
  flutter_animated_login: ^0.0.12
  lottie: ^2.2.0
  url_launcher: ^6.0.10
  razorpay_flutter: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:
  uses-material-design: true

